Additional source and playlist collection fix
norkunas/youtube-dl-php pull request #174
Opened 2021-12-28 13:57 UTC by Mrlaminat

2021-12-28 14:08 UTC, norkunas requested changes
Thanks for your findings :)

2021-12-28 14:08 UTC, norkunas commented on src/YoutubeDl.php
> +            ) {
```suggestion
            if (preg_match('/\[(?<extractor>.+)]\s(?<id>.+):\sDownloading( pc )?webpage/', $buffer, $match) === 1) {
```

2021-12-28 14:08 UTC, norkunas commented on src/YoutubeDl.php
>                  $currentVideo['extractor'] = $match[1];
```suggestion
                $currentVideo['extractor'] = $match['extractor'];
                $currentVideo['id'] = $match['id'];
```

2021-12-28 14:08 UTC, norkunas commented on src/YoutubeDl.php
>                  $currentVideo['extractor'] = $match[1];
can't suggest for two lines, so just `$currentVideo['id'] = $match[2];` with `$currentVideo['id'] = $match['id'];`

2021-12-28 14:09 UTC, norkunas commented
Would be nice to add a test that it properly parses output with the `pc` in it

2021-12-28 15:02 UTC, Mrlaminat commented on src/YoutubeDl.php
> +            ) {
Yeah, this one looks much better :)

2021-12-28 15:03 UTC, Mrlaminat commented
> Would be nice to add a test that it properly parses output with the `pc` in it

Need to check how tests are implemented for your system. Is it has some prepared URL?

2021-12-28 16:38 UTC, norkunas commented
> > Would be nice to add a test that it properly parses output with the `pc` in it
> 
> Need to check how tests are implemented for your system. Is it has some prepared URL?

No, it does not do real requests, only tests how it works with the stream output

2021-12-28 19:46 UTC, Mrlaminat commented
@norkunas Fixed regex. 

PS. I would recommend you add a regex container, from which all regexes could be tested. It will help to cover more supported platforms without huge regex complexity. If you worrying about performance, maybe you can add a function flag ("useMultiplePlatformRegex", by default false).

2021-12-29 04:41 UTC, norkunas commented
@Mrlaminat I'm not against it, but currently regexes are simple enough not to introduce your suggested regex container. We'll see in future if it become hard to maintain then it probably will be time for that.
Will you be able to write a test for this?

2021-12-29 04:43 UTC, norkunas commented
Also I'm curious which source adds the `pc` to that sentence? Or is it with the yt-dlp that it adds different source to it?

2021-12-29 08:46 UTC, Mrlaminat commented
> @Mrlaminat I'm not against it, but currently regexes are simple enough not to introduce your suggested regex container. We'll see in future if it become hard to maintain then it probably will be time for that. Will you be able to write a test for this?

It was just suggestion for the future, right now is good enough!

I just fixed code to pass already existed tests, from my local env I even can't run them with xDebug so it's difficult to find how to create a new one.

LIke for me it works perfect, and it's not broke usuall youtube flow, so looks like we are okay :)

2021-12-29 08:47 UTC, norkunas commented
just run with XDEBUG_MODE=off :)

2021-12-29 08:58 UTC, Mrlaminat commented
But I need to enable, not disable :) 
Anyway, what do you want from new tests? why old one is not satisfied you ?

2021-12-29 08:59 UTC, norkunas commented
Oh, and why do you need to run with it ? :D
Because there are not tests that covers the part with `Downloading pc webpage` so it's better to have at least 1 test to not break this accidentally in future :)

2021-12-29 09:01 UTC, Mrlaminat commented
> Oh, and why do you need to run with it ? :D Because there are not tests that covers the part with `Downloading pc webpage` so it's better to have at least 1 test to not break this accidentally in future :)

I'm not good at unit testing, finding why the previose failing was paitful :)

2021-12-29 09:02 UTC, norkunas commented
Ok then if you'd like for me to add the test, could you run the lib in debug mode and give me all output it prints?

2021-12-29 09:29 UTC, Mrlaminat commented
Whatever, Good time for learning. I'll add it

2021-12-29 10:58 UTC, norkunas commented
Why you have closed this?

2021-12-29 13:47 UTC, Mrlaminat commented
@norkunas changed my mind. Sorry for the confusion and thank you

2021-12-29 13:49 UTC, norkunas commented
Just not to bother you, open and I'll merge as is :bow:

2021-12-29 13:50 UTC, norkunas approved these changes

2021-12-29 13:51 UTC, merged

2021-12-29 13:51 UTC, norkunas commented
Thank you!

2021-12-29 19:01 UTC, Mrlaminat commented
Man, that's a Great project, thank you for developing and maintaining it!