Fix not returning mp3 file with yt-dlp
norkunas/youtube-dl-php pull request #175
Opened 2022-01-10 13:09 UTC by MichaelBelgium

Issue noticed in https://github.com/norkunas/youtube-dl-php/issues/162#issuecomment-1008836480
Tested the regex here: https://regex101.com/r/sqwPFw/1

Tested and returned a var dump of `getFile()` and returns
```
object(SplFileInfo)#9 (2) {
  ["pathName":"SplFileInfo":private]=>
  string(24) "download/_VeNOH9i06I.mp3"
  ["fileName":"SplFileInfo":private]=>
  string(15) "_VeNOH9i06I.mp3"
}
```

2022-01-10 14:36 UTC, norkunas commented
Would you be able to add a test covering this?

2022-01-10 19:08 UTC, norkunas commented
Yes, you're on the right path

2022-01-11 05:21 UTC, norkunas commented
Now you should also add cases to YoutubeDlTest.php using that outputs :)

2022-01-11 05:27 UTC, norkunas requested changes

2022-01-11 05:27 UTC, norkunas commented on tests/Fixtures/youtube-dl/youtube/phonebloks-mp3.txt
> +[info] Writing video description metadata as JSON to: ./oDAw7vW7H0c.info.json
And as in the tests virtual filesystem is used, then this path should be:

```suggestion
[info] Writing video description metadata as JSON to: vfs://yt-dl/oDAw7vW7H0c.info.json
```

2022-01-11 05:27 UTC, norkunas commented on tests/Fixtures/youtube-dl/youtube/phonebloks-mp3.txt
> +[download] Destination: ./oDAw7vW7H0c.webm
```suggestion
[download] Destination: vfs://yt-dl/oDAw7vW7H0c.webm
```

2022-01-11 05:27 UTC, norkunas commented on tests/Fixtures/youtube-dl/youtube/phonebloks-mp3.txt
> +[ffmpeg] Destination: ./oDAw7vW7H0c.mp3
```suggestion
[ffmpeg] Destination: vfs://yt-dl/oDAw7vW7H0c.mp3
```

2022-01-11 05:27 UTC, norkunas commented on tests/Fixtures/youtube-dl/youtube/phonebloks-mp3.txt
> +Deleting original file ./oDAw7vW7H0c.webm (pass -k to keep)
```suggestion
Deleting original file vfs://yt-dl/oDAw7vW7H0c.webm (pass -k to keep)
```

2022-01-11 05:27 UTC, norkunas commented on tests/Fixtures/yt-dlp/youtube/phonebloks-mp3.txt
> +[info] Writing video metadata as JSON to: ./oDAw7vW7H0c.info.json
```suggestion
[info] Writing video metadata as JSON to: vfs://yt-dl/oDAw7vW7H0c.info.json
```

2022-01-11 05:27 UTC, norkunas commented on tests/Fixtures/yt-dlp/youtube/phonebloks-mp3.txt
> +[download] Destination: ./oDAw7vW7H0c.webm
```suggestion
[download] Destination: vfs://yt-dl/oDAw7vW7H0c.webm
```

2022-01-11 05:27 UTC, norkunas commented on tests/Fixtures/yt-dlp/youtube/phonebloks-mp3.txt
> +[ExtractAudio] Destination: ./oDAw7vW7H0c.mp3
```suggestion
[ExtractAudio] Destination: vfs://yt-dl/oDAw7vW7H0c.mp3
```

2022-01-11 05:27 UTC, norkunas commented on tests/Fixtures/yt-dlp/youtube/phonebloks-mp3.txt
> +Deleting original file ./oDAw7vW7H0c.webm (pass -k to keep)
```suggestion
Deleting original file vfs://yt-dl/oDAw7vW7H0c.webm (pass -k to keep)
```

2022-01-11 13:03 UTC, MichaelBelgium commented
> Now you should also add cases to YoutubeDlTest.php using that outputs :)

Well it never can be _exactly_ the same right? Like the download speeds and stuff?

I add a function `testDownloadMp3` or something like that? Like [here](https://github.com/norkunas/youtube-dl-php/blob/master/tests/YoutubeDlTest.php#L178-L195)
Or how to say it needs to assert that output with `download()` ... etc

You can tell i don't write a lot of tests 😂

2022-01-11 13:10 UTC, norkunas commented
Download speeds doesn't matter :) it's just enough to ensure that it can properly parse the output and create a video collection from the downloaded metadata file

2022-01-11 20:18 UTC, MichaelBelgium commented
I came up with this test but its probably not the right approach.

When executing `vendor\bin\simple-phpunit` it says it's a risky test and doesn't assert anything?


```
public function provideMp3VideoFile(): iterable
    {
        $expectedFile = new SplFileInfo('vfs://yt-dl/oDAw7vW7H0c.mp3');

        yield 'youtube-dl: phonebloks' => [
            'url' => 'https://www.youtube.com/watch?v=oDAw7vW7H0c',
            'outputFile' => __DIR__.'/Fixtures/youtube-dl/youtube/phonebloks-mp3.txt',
            'expectedEntity' => new Video(['file' => $expectedFile]),
        ];

        yield 'yt-dlp: phonebloks' => [
            'url' => 'https://www.youtube.com/watch?v=oDAw7vW7H0c',
            'outputFile' => __DIR__.'/Fixtures/yt-dlp/youtube/phonebloks-mp3.txt',
            'expectedEntity' => new Video(['file' => $expectedFile]),
        ];
    }
```

2022-01-12 04:31 UTC, norkunas commented
Tests looks fine :) just add the metadata files to fix them

2022-01-12 09:58 UTC, MichaelBelgium commented
Isn't the metafile already there? [This](https://github.com/norkunas/youtube-dl-php/blob/master/tests/Fixtures/youtube-dl/youtube/Phonebloks-oDAw7vW7H0c.info.json) one, Or am i missing something

I don't get the phpunit error

2022-01-12 10:06 UTC, norkunas commented
It's there, but it is used as for video download, not for mp3. This library builds the VideoCollection/Video from the metadata, but before doing that it also appends `_filename` to the end file, so to mimick that we need the new one metadata file for mp3 which you'd get to your device if you'd run with `cleanupMetadata(false)` option.

2022-01-12 18:50 UTC, MichaelBelgium commented
So i just replace the old one with the mp3 metadata one?

2022-01-13 06:18 UTC, norkunas commented
I've fixed the tests, but cannot push to your PR. Did you enable this?:
![image](https://user-images.githubusercontent.com/2722872/149276111-1aaab27b-49de-469f-ae6e-9d53012f3bc7.png)

2022-01-13 07:52 UTC, MichaelBelgium commented
Now i did :)

2022-01-13 08:00 UTC, norkunas approved these changes

2022-01-13 08:00 UTC, merged

2022-01-13 08:00 UTC, norkunas commented
Thank you :)